# Generated by Django 6.0.6 on 2026-08-19 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('actor_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('actor_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('panel', models.CharField(db_index=True, max_length=64)),
                ('operation', models.CharField(db_index=True, max_length=64)),
                ('target_ref', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('outcome', models.CharField(choices=[('conflict', 'rejected before any write'), ('success', 'completed and verified'), ('partial', 'wrote, then faulted; do not retry'), ('recovery_required', 'wrote, then faulted; needs operator action'), ('indeterminate', 'started, outcome unknown; do not retry')], db_index=True, default='success', max_length=24)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('inverse', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('retention', models.CharField(choices=[('normal', 'pruned on the standard window'), ('repl', 'pruned on the REPL window'), ('permanent', 'never pruned')], db_index=True, default='normal', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Console audit event',
                'verbose_name_plural': 'Console audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_id', '-created_at'], name='console_con_actor_i_5fc0b3_idx'), models.Index(fields=['panel', 'operation', '-created_at'], name='console_con_panel_ee1776_idx'), models.Index(fields=['target_ref', '-created_at'], name='console_con_target__4bca2f_idx'), models.Index(fields=['outcome', '-created_at'], name='console_con_outcome_d55522_idx')],
            },
        ),
    ]
