# Generated by Django 6.0.6 on 2026-08-20 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleErrorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(db_index=True, max_length=64, unique=True)),
                ('state', models.CharField(choices=[('open', 'awaiting review'), ('acknowledged', 'seen, still happening'), ('muted', 'known, hide until the signature changes')], db_index=True, default='open', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Console error state',
                'verbose_name_plural': 'Console error states',
                'ordering': ['-updated_at'],
            },
        ),
    ]
