# Generated by Django 6.0.6 on 2026-08-20 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_consoleerrorstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('panel', models.CharField(db_index=True, max_length=64)),
                ('query', models.CharField(blank=True, default='', max_length=1000)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('pinned', models.BooleanField(db_index=True, default=False)),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Console saved view',
                'verbose_name_plural': 'Console saved views',
                'ordering': ['panel', 'name'],
                'constraints': [models.UniqueConstraint(fields=('panel', 'name'), name='console_view_unique_name')],
            },
        ),
    ]
