# Generated by Django 6.0.4 on 2026-05-06 18:28

import typeclasses.caching_db
import typeclasses.mixins.furniture_mixin
import typeclasses.mixins.medical_mixin
import typeclasses.mixins.roleplay_mixin
import typeclasses.mixins.rpg_character_mixin
import typeclasses.objects
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultObject",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.objectdb",),
        ),
        migrations.CreateModel(
            name="DefaultCharacter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="DefaultExit",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="DefaultRoom",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="Object",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(typeclasses.objects.ObjectParent, "objects.defaultobject"),
        ),
        migrations.CreateModel(
            name="Character",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                typeclasses.caching_db.DbCacheInvalidationMixin,
                typeclasses.mixins.roleplay_mixin.RoleplayMixin,
                typeclasses.mixins.medical_mixin.MedicalMixin,
                typeclasses.mixins.rpg_character_mixin.RPGCharacterMixin,
                typeclasses.mixins.furniture_mixin.FurnitureMixin,
                typeclasses.objects.ObjectParent,
                "objects.defaultcharacter",
            ),
        ),
    ]
