# Generated by Django 6.0.5 on 2026-06-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0018_remove_objectdb_db_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.object",),
        ),
        migrations.CreateModel(
            name="ChemicalItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.item",),
        ),
        migrations.CreateModel(
            name="CompoundItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.item",),
        ),
        migrations.CreateModel(
            name="DigitalDocument",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.item",),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.item",),
        ),
        migrations.CreateModel(
            name="DrugItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.item",),
        ),
    ]
