# Generated by Django 6.0.5 on 2026-05-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_gameevent_enginejob"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gameevent",
            new_name="server_game_subject_40e896_idx",
            old_name="server_game_subject_0e8f0d_idx",
        ),
        migrations.AlterField(
            model_name="enginejob",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="gameevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
