# Generated by Django 6.0.5 on 2026-07-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "server",
            "0005_rename_server_game_subject_0e8f0d_idx_server_game_subject_40e896_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="enginejob",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enginejob",
            name="available_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="enginejob",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enginejob",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="enginejob",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="enginejob",
            name="lease_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="enginejob",
            name="max_attempts",
            field=models.IntegerField(default=5),
        ),
        migrations.AddIndex(
            model_name="enginejob",
            index=models.Index(
                fields=["status", "priority", "created_at"],
                name="server_engi_status_6b2363_idx",
            ),
        ),
    ]
