# Generated by Django 6.0.5 on 2026-07-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0006_enginejob_attempts_enginejob_available_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizationPrincipalState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("principal_ref", models.CharField(max_length=128, unique=True)),
                ("suspended", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("suspended_until", models.DateTimeField(blank=True, null=True)),
                ("generation", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizationAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("kind", models.CharField(db_index=True, max_length=64)),
                (
                    "principal_ref",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "capability",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "resource_ref",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("actor_ref", models.CharField(blank=True, default="", max_length=128)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["principal_ref", "-created_at"],
                        name="authaudit_principal_idx",
                    ),
                    models.Index(fields=["kind", "-created_at"], name="authaudit_kind_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grant_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("principal_ref", models.CharField(max_length=128)),
                ("capability", models.CharField(max_length=128)),
                ("scope_kind", models.CharField(max_length=32)),
                ("scope_key", models.CharField(max_length=255)),
                ("constraints", models.JSONField(default=dict)),
                (
                    "provenance",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "parent_grant_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["principal_ref", "capability", "revoked_at"],
                        name="authgrant_principal_cap_idx",
                    ),
                    models.Index(fields=["expires_at"], name="authgrant_expires_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=(
                            "principal_ref",
                            "capability",
                            "scope_kind",
                            "scope_key",
                        ),
                        name="authgrant_active_scope_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationPolicyOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_ref", models.CharField(max_length=160)),
                ("access_type", models.CharField(max_length=64)),
                (
                    "template_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("policy", models.JSONField(default=dict)),
                ("policy_version", models.PositiveIntegerField(default=1)),
                ("legacy_shadow", models.TextField(blank=True, default="")),
                ("legacy_frozen", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["resource_ref"], name="authpolicy_resource_idx"),
                    models.Index(fields=["legacy_frozen"], name="authpolicy_frozen_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource_ref", "access_type"),
                        name="authpolicy_resource_access_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorizationScopeLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_ref", models.CharField(max_length=160)),
                ("label", models.CharField(max_length=255)),
                ("source", models.CharField(default="authored", max_length=32)),
                ("generation", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["resource_ref"], name="authscope_resource_idx"),
                    models.Index(fields=["label", "resource_ref"], name="authscope_label_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource_ref", "label"),
                        name="authscope_resource_label_uniq",
                    )
                ],
            },
        ),
    ]
