# Generated by Django 6.0.6 on 2026-08-20 10:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_sanction_sessionrecord_moderationflag_sanctionhit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(db_index=True, max_length=32)),
                ('subject_value', models.CharField(db_index=True, max_length=255)),
                ('level', models.CharField(db_index=True, max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('staff_note', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('collateral', models.JSONField(blank=True, default=dict)),
                ('proposed_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('proposed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('pending', 'awaiting a decision'), ('approved', 'approved, sanction issued'), ('declined', 'reviewed, refused'), ('withdrawn', 'withdrawn by the person who asked')], db_index=True, default='pending', max_length=16)),
                ('decided_by_id', models.IntegerField(blank=True, null=True)),
                ('decided_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=500)),
                ('flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='server.moderationflag')),
                ('sanction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='server.sanction')),
            ],
            options={
                'verbose_name': 'Sanction proposal',
                'verbose_name_plural': 'Sanction proposals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', '-created_at'], name='server_sanc_state_831b0c_idx'), models.Index(fields=['subject_type', 'subject_value'], name='server_sanc_subject_4c79d5_idx')],
            },
        ),
    ]
