"""Generate TypeScript types for the merged OOB event catalog.

    <venv>/python -m evennia.server.protocol.gen_ts [output.ts]

Walks the registry (engine core + all PROTOCOL_EVENT_MODULES), so the emitted
types cover both engine and game events. Default output is the web shell's
lib/oob-events.ts. Run after adding or changing an event.
"""

import os
import sys

from evennia.server.protocol import all_events

_TS = {
    "str": "string",
    "int": "number",
    "float": "number",
    "bool": "boolean",
    "list": "any[]",
    "dict": "Record<string, any>",
    "any": "any",
}

_DEFAULT_OUT = os.path.normpath(
    os.path.join(
        os.path.dirname(__file__),
        "..",
        "..",
        "web",
        "webclient",
        "client",
        "src",
        "lib",
        "oob-events.ts",
    )
)


def _pascal(name):
    return "".join(p.capitalize() for p in name.split("_"))


def _emit(name, spec):
    fields = spec["fields"]
    pascal = _pascal(name)
    lines = []
    if spec.get("doc"):
        lines.append(f"/** {spec['doc']} */")
    if "_" in fields:
        lines.append(f"export type {pascal}Payload = {_TS[fields['_']]};")
    elif "_map" in fields:
        lines.append(f"export type {pascal}Payload = Record<string, {_TS[fields['_map']]}>;")
    else:
        lines.append(f"export interface {pascal}Payload {{")
        for fname, ftype in fields.items():
            optional = fname.endswith("?")
            key = fname[:-1] if optional else fname
            lines.append(f"  {key}{'?' if optional else ''}: {_TS[ftype]};")
        lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    events = all_events()
    out = [
        "// AUTO-GENERATED by evennia.server.protocol.gen_ts from the OOB event registry.",
        "// Do not edit by hand; edit the event modules and regenerate.",
        "",
    ]
    for name, spec in sorted(events.items()):
        out.append(_emit(name, spec))
        out.append("")
    out.append("export type OobEvent =")
    out.append("  | " + "\n  | ".join(f'"{n}"' for n in sorted(events)) + ";")
    out.append("")
    out.append("export interface OobEventMap {")
    for name in sorted(events):
        out.append(f'  "{name}": {_pascal(name)}Payload;')
    out.append("}")
    out.append("")
    return "\n".join(out)


def main():
    # Configure settings if invoked standalone from a game dir.
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "server.conf.settings")
    import django

    django.setup()
    path = sys.argv[1] if len(sys.argv) > 1 else _DEFAULT_OUT
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(generate())
    print(f"wrote {path} ({len(all_events())} events)")


if __name__ == "__main__":
    main()
