# Generated by Django 5.1.6 on 2025-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Replace index_together with Index on Tag.

    Adds the long auto-style name first; 0018 renames to typeclasses_db_key_be0c81_idx.
    (Previous get_operations() + operations=[] never ran any ops on fresh databases.)
    """

    dependencies = [
        ("typeclasses", "0016_alter_attribute_id_alter_tag_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["db_key", "db_category", "db_tagtype", "db_model"],
                name="typeclasses_tag_db_key_db_category_db_tagtype_db_model_idx",
            ),
        ),
    ]
