# Generated by Django 6.0.4 on 2026-05-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("typeclasses", "0017_use_index_instead_of_index_together_in_tags"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tag",
            new_name="typeclasses_db_key_be0c81_idx",
            old_fields=("db_key", "db_category", "db_tagtype", "db_model"),
        ),
    ]
