# Generated by Django 6.0.5 on 2026-06-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("typeclasses", "0022_attribute_typed_value_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attribute",
            name="attr_valtype_int_idx",
        ),
        migrations.RemoveIndex(
            model_name="attribute",
            name="attr_valtype_float_idx",
        ),
        migrations.DeleteModel(
            name="Attribute",
        ),
    ]
