# Generated by Django 6.0.5 on 2026-06-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("typeclasses", "0022_attribute_typed_value_indexes"),
        # Through-table FKs pointing at typeclasses_attribute must be dropped first.
        ("objects", "0018_remove_objectdb_db_attributes"),
        ("accounts", "0017_remove_accountdb_db_attributes"),
        ("scripts", "0023_remove_scriptdb_db_attributes"),
        ("comms", "0027_remove_channeldb_db_attributes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attribute",
            name="attr_valtype_int_idx",
        ),
        migrations.RemoveIndex(
            model_name="attribute",
            name="attr_valtype_float_idx",
        ),
        migrations.DeleteModel(
            name="Attribute",
        ),
    ]
