#!/usr/bin/env python3
"""
Phase 3 recon: cmdset prefix audit.

Walks every default cmdset shipped by Evennia, captures the static
inventory of command keys/aliases, and emits a deterministic markdown
table. The output is the frozen artifact downstream consumers diff
against when planning Phase 3 migrations.

The convention this audit supports is documented in
``.agents/docs/code-style.md`` (Command Naming). Briefly: ``@``-prefix
for player/account/OOC actions, no prefix for IC actions. The audit
itself does not enforce the convention; it just dumps current state
so reviewers can compare against the doc.

Run from the test game dir (bootstrapped Django settings)::

    cd .test_game_dir
    uv run python ../.agents/tools/cmdset_prefix_audit.py --write
    uv run python ../.agents/tools/cmdset_prefix_audit.py --check

Modes:
    --write  Overwrite ``PHASE3_AUDIT.md`` at the repo root with the
             current inventory.
    --check  Re-generate the inventory in-memory and diff against the
             committed file. Exit 1 on any difference. CI mode.

Default (no flag): print the inventory to stdout, exit 0.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "PHASE3_AUDIT.md"

# Default cmdsets shipped by the engine. Order matters: it determines
# the section order in the generated manifest.
DEFAULT_CMDSETS = (
    ("evennia.commands.default.cmdset_character", "CharacterCmdSet"),
    ("evennia.commands.default.cmdset_account", "AccountCmdSet"),
    ("evennia.commands.default.cmdset_session", "SessionCmdSet"),
    ("evennia.commands.default.cmdset_unloggedin", "UnloggedinCmdSet"),
)


def _coerce_aliases(aliases) -> list[str]:
    """Normalise ``aliases`` to a sorted list of strings.

    Args:
        aliases: Whatever a Command class declared. May be a list,
            tuple, single string, or absent.

    Returns:
        list[str]: Aliases sorted ascending. Empty list if none.

    """
    if not aliases:
        return []
    if isinstance(aliases, str):
        return [aliases]
    return sorted(str(a) for a in aliases)


def _row_for_command(cmd) -> dict:
    """Extract auditable fields from a Command instance.

    Args:
        cmd: A Command instance taken from a populated cmdset.

    Returns:
        dict: ``{class_name, module, key, aliases, account_command_caller, locks}``.

    """
    return {
        "class_name": type(cmd).__name__,
        "module": type(cmd).__module__,
        "key": cmd.key,
        "aliases": _coerce_aliases(cmd.aliases),
        "account_command_caller": bool(getattr(cmd, "account_command_caller", False)),
        "locks": str(cmd.locks),
    }


def audit_cmdsets(cmdset_classes: Iterable) -> list[dict]:
    """Walk each cmdset class and produce a structured inventory.

    Args:
        cmdset_classes: Iterable of CmdSet classes. Each will be
            instantiated; its ``at_cmdset_creation`` method runs to
            populate the cmdset.

    Returns:
        list[dict]: One entry per cmdset, in the order supplied:
            ``{"cmdset": str, "commands": [row_for_command, ...]}``.
            Commands within a cmdset are sorted by key.

    """
    out = []
    for cmdset_cls in cmdset_classes:
        cmdset = cmdset_cls()
        if hasattr(cmdset, "at_cmdset_creation"):
            cmdset.at_cmdset_creation()
        rows = [_row_for_command(cmd) for cmd in cmdset.commands]
        rows.sort(key=lambda r: (r["key"], r["class_name"]))
        out.append({"cmdset": type(cmdset).__name__, "commands": rows})
    return out


def format_markdown(audit_data: list[dict]) -> str:
    """Render the audit data as a deterministic markdown document.

    Args:
        audit_data: Output of :func:`audit_cmdsets`.

    Returns:
        str: Markdown text with one section per cmdset. Trailing newline.

    """
    lines = [
        "# Phase 3 cmdset prefix audit",
        "",
        "Generated by `.agents/tools/cmdset_prefix_audit.py`. Do not edit by hand.",
        "Regenerate with `cmdset_prefix_audit.py --write`. CI runs `--check`",
        "to detect drift. See `.agents/docs/code-style.md` (Command Naming)",
        "for the convention this inventory is reviewed against.",
        "",
        "Columns:",
        "",
        "- **key** — the command's registered key. `@`-prefix indicates OOC by convention.",
        "- **aliases** — comma-separated, sorted. Should match the key's prefix status.",
        "- **acct** — value of `account_command_caller`. Most OOC commands set this; some",
        "  OOC actions (e.g. `emit`, `force`) intentionally keep character-level caller.",
        "- **class** — `module.ClassName` for traceability.",
        "- **locks** — current locks string.",
        "",
    ]
    for section in audit_data:
        lines.append(f"## {section['cmdset']}")
        lines.append("")
        if not section["commands"]:
            lines.append("_(empty)_")
            lines.append("")
            continue
        lines.append("| key | aliases | acct | class | locks |")
        lines.append("|---|---|---|---|---|")
        for row in section["commands"]:
            aliases = ", ".join(row["aliases"]) if row["aliases"] else ""
            acct = "yes" if row["account_command_caller"] else ""
            cls = f"{row['module']}.{row['class_name']}"
            lines.append(f"| `{row['key']}` | {aliases} | {acct} | `{cls}` | `{row['locks']}` |")
        lines.append("")
    return "\n".join(lines) + "\n"


def _load_default_cmdset_classes():
    """Resolve the default cmdset class objects.

    Returns:
        list: Cmdset classes, in :data:`DEFAULT_CMDSETS` order.

    Raises:
        ImportError: If a cmdset module fails to import. This usually
            means Django is not yet set up.

    """
    import importlib

    resolved = []
    for module_path, class_name in DEFAULT_CMDSETS:
        module = importlib.import_module(module_path)
        resolved.append(getattr(module, class_name))
    return resolved


def _bootstrap_django() -> None:
    """Initialise Django enough to instantiate cmdsets.

    Caller is expected to run from a directory whose settings are
    importable as ``server.conf.settings`` (i.e. inside a game dir
    like ``.test_game_dir``). Falls back to ``evennia.settings_default``
    if the game settings module is not importable, which is sufficient
    for the audit but lacks DB tables.

    """
    import os

    import django

    if not os.environ.get("DJANGO_SETTINGS_MODULE"):
        try:
            import server.conf.settings  # noqa: F401

            os.environ["DJANGO_SETTINGS_MODULE"] = "server.conf.settings"
        except ImportError:
            os.environ["DJANGO_SETTINGS_MODULE"] = "evennia.settings_default"
    django.setup()

    # The default cmdset modules import building.py which transitively
    # touches evennia.utils.evmenu — its module-level CmdEvMenuNode
    # class needs evennia.Command resolved, which only happens after
    # evennia._init() runs. Without this we get a NoneType TypeError
    # at evmenu import time.
    import evennia

    evennia._init()


def _check_against_manifest(generated: str) -> int:
    """Compare freshly generated audit text against the committed manifest.

    Args:
        generated: Markdown text produced by :func:`format_markdown`.

    Returns:
        int: ``0`` on match, ``1`` on drift or missing manifest. Prints
            a unified diff to stderr on drift.

    """
    if not MANIFEST_PATH.exists():
        print(
            f"ERROR: {MANIFEST_PATH} does not exist. " "Generate it once with `--write`.",
            file=sys.stderr,
        )
        return 1
    committed = MANIFEST_PATH.read_text()
    if committed == generated:
        return 0
    import difflib

    diff = difflib.unified_diff(
        committed.splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile=str(MANIFEST_PATH),
        tofile="(regenerated)",
    )
    print("ERROR: PHASE3_AUDIT.md is out of date.\n", file=sys.stderr)
    sys.stderr.writelines(diff)
    print(
        "\nRun `.agents/tools/cmdset_prefix_audit.py --write` to refresh.",
        file=sys.stderr,
    )
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--write",
        action="store_true",
        help=f"Overwrite {MANIFEST_PATH.name} with current inventory.",
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="Compare in-memory inventory against the committed manifest. CI mode.",
    )
    args = parser.parse_args(argv)

    _bootstrap_django()
    cmdset_classes = _load_default_cmdset_classes()
    audit_data = audit_cmdsets(cmdset_classes)
    rendered = format_markdown(audit_data)

    if args.write:
        MANIFEST_PATH.write_text(rendered)
        print(f"Wrote {MANIFEST_PATH}")
        return 0
    if args.check:
        return _check_against_manifest(rendered)
    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
