import { describe, expect, it } from "vitest";

import cases from "./__fixtures__/markup-parity.json";
import { looksLikeHtml, pipeToHtml } from "./markup";

// The shell may render pipe-codes itself instead of using the server's parsed
// `html` (see the `rendersMarkup` cap). That is only safe while the two parsers
// agree, so every case here is the server's own parse_html output, generated by
// scripts/gen-markup-parity.py. Regenerate that fixture if the server parser
// changes; a diff here means the client would render something else.

describe("pipeToHtml matches server parse_html", () => {
  for (const { src, html } of cases as { src: string; html: string }[]) {
    it(JSON.stringify(src), () => {
      expect(pipeToHtml(src)).toBe(html);
    });
  }
});

describe("pipeToHtml escaping", () => {
  it("escapes html-significant characters in text", () => {
    expect(pipeToHtml("<script>")).toBe("&lt;script&gt;");
  });

  it("escapes inside a coloured span", () => {
    expect(pipeToHtml("|r<b>|n")).toBe('<span class="color-009">&lt;b&gt;</span>');
  });
});

describe("looksLikeHtml", () => {
  it("detects server-parsed markup", () => {
    expect(looksLikeHtml('<span class="color-009">x</span>')).toBe(true);
  });

  it("does not fire on plain pipe-coded text", () => {
    expect(looksLikeHtml("|rred|n")).toBe(false);
  });
});
