import { describe, expect, it } from "vitest";

import cases from "./__fixtures__/markup-parity.json";
import { looksLikeHtml, pipeToHtml } from "./markup";

// The shell may render pipe-codes itself instead of using the server's parsed
// `html` (see the `rendersMarkup` cap). That is only safe while the two parsers
// agree, so every case here is the server's own parse_html output, generated by
// scripts/gen-markup-parity.py. Regenerate that fixture if the server parser
// changes; a diff here means the client would render something else.

describe("pipeToHtml matches server parse_html", () => {
  for (const { src, html } of cases as { src: string; html: string }[]) {
    it(JSON.stringify(src), () => {
      expect(pipeToHtml(src)).toBe(html);
    });
  }
});

describe("pipeToHtml escaping", () => {
  it("serializes backslashes before escaping command attributes", () => {
    expect(pipeToHtml('|lcsay \\"hi"|lt"click"|le')).toBe(
      '<a id="mxplink" href="#" onclick="Evennia.msg(&quot;text&quot;,[&quot;say \\\\\\&quot;hi\\&quot;&quot;],{});return false;">"click"</a>',
    );
  });

  it.each([
    ["|#f00red|n", '<span class="" style="color: #ff0000;">red</span>'],
    ["|#Ff0000red|n", '<span class="" style="color: #ff0000;">red</span>'],
    ["|[#0f0green|n", '<span class="" style="background-color: #00ff00;">green</span>'],
    ["|[#0000FFblue|n", '<span class="" style="background-color: #0000ff;">blue</span>'],
    ["|#1234text|n", '<span class="" style="color: #112233;">4text</span>'],
    ["|#1234567text|n", '<span class="" style="color: #123456;">7text</span>'],
    ["||#f00 literal", "|#f00 literal"],
    ["|#12no|n", "|#12no"],
    ["|[#xyzno|n", "|[#xyzno"],
    ["|#f00red|nplain", '<span class="" style="color: #ff0000;">red</span>plain'],
  ])("renders hex markup %s", (src, html) => {
    expect(pipeToHtml(src)).toBe(html);
  });

  it("escapes html-significant characters in text", () => {
    expect(pipeToHtml("<script>")).toBe("&lt;script&gt;");
  });

  it("escapes inside a coloured span", () => {
    expect(pipeToHtml("|r<b>|n")).toBe('<span class="color-009">&lt;b&gt;</span>');
  });
});

describe("looksLikeHtml", () => {
  it("detects server-parsed markup", () => {
    expect(looksLikeHtml('<span class="color-009">x</span>')).toBe(true);
  });

  it("does not fire on plain pipe-coded text", () => {
    expect(looksLikeHtml("|rred|n")).toBe(false);
  });
});
