// AUTO-GENERATED by evennia.server.protocol.gen_ts from the OOB event registry.
// Do not edit by hand; edit the event modules and regenerate.

export interface PlayAudioPayload {
  url: string;
  loop?: boolean;
  volume?: number;
  fade_in?: number;
}

export interface SetAudioVolumePayload {
  volume: number;
  fade?: number;
}

export interface StopAudioPayload {
  fade_out?: number;
}

export interface AssistInboxPayload {
  threads: any[];
}

export interface AssistThreadPayload {
  account_id: any;
  account_key: string;
  messages: any[];
}

/** args[0] = audio URL. */
export type AudioPayload = string;

/** channel_key -> list of message rows. */
export type ChannelHistoryPayload = Record<string, Record<string, any>>;

export interface ChannelMsgPayload {
  channel: string;
  text: string;
  html?: string;
  sender: string;
  sender_html?: string;
  platform?: string;
  ts: number;
  msg_id: string;
}

export interface ChannelMsgDeletePayload {
  channel: string;
  msg_id: string;
}

/** channel_key -> count. */
export type ChannelOnlinePayload = Record<string, Record<string, any>>;

export interface ChannelPinPayload {
  channel_key: string;
  action?: string;
  msg_id?: string;
  text?: string;
  pinned_by?: string;
}

export interface ChannelReactionPayload {
  channel_key: string;
  msg_id: string;
  emoji: string;
  count?: number;
  delta?: number;
  sender_name?: string;
}

export interface ChannelTopicPayload {
  channel_key: string;
  topic: string;
}

export interface ChannelTypingPayload {
  channel_key: string;
  sender_name: string;
  platform?: string;
}

/** channel_key -> count. */
export type ChannelUnreadPayload = Record<string, Record<string, any>>;

/** Full channel registry; args[0] is a list of channel dicts. */
export type ChannelsListPayload = any[];

export interface CommunityKudosPayload {
  receiver: string;
  message: string;
  anonymous: boolean;
  giver?: string;
}

export interface CommunityMilestonePayload {
  label: string;
}

/** Live preview of a pose/emote/say before it is sent. */
export interface ComposePreviewPayload {
  you: string;
  room: string;
  error?: string;
}

/** args[0] = session_id; the server closed the editor. */
export type EditorClosePayload = string;

/** args = [session_id, buffer, meta]; open the editor overlay. */
export type EditorOpenPayload = any[];

/** args[0] = 'saved' | 'unsaved'. */
export type EditorStatusPayload = string;

/** args[0] = image URL. */
export type ImagePayload = string;

/** args[0] = reason (e.g. 'quit'). */
export type LogoutPayload = string;

/** args[0] = audio URL. */
export type PlayMusicPayload = string;

/** args = [yt_id, offset_seconds, loop(0|1)]; start room/DJ music. */
export type PlayYtPayload = any[];

export interface PlayerMentionPayload {
  channel: string;
  msg_id: string;
  sender: string;
  text: string;
}

/** Fade the current track out. */
export interface StopMusicPayload {
  fade_out?: number;
}

/** Cut playback immediately. */
export type StopMusicNowPayload = any;

export interface TicketAlertPayload {
  id: string;
  label: string;
  who: string;
  age_mins: number;
}

export interface TicketInboxPayload {
  tickets: any[];
}

export interface TicketMsgPayload {
  id: string;
  kind: string;
  text: string;
  html?: string;
  sender: string;
  sender_html?: string;
  platform?: string;
  visibility?: string;
  ts: number;
  status?: string;
}

/** A full ticket dict (see tickets.core.to_dict). */
export type TicketThreadPayload = Record<string, any>;

/** A UI component spec (see evennia.server.ui). */
export type UiComponentPayload = Record<string, any>;

export interface UiRemovePayload {
  id: string;
}

/** args[0] = video URL. */
export type VideoPayload = string;

/** Open an embedded web page in the shell: args[0] = {url, title?, id?}. */
export type WebPanelPayload = Record<string, any>;

/** args[0] = YouTube URL. */
export type YoutubePayload = string;

/** args[0] = 1|0. */
export type YtSetLoopPayload = number;

export type OobEvent =
  | "PLAY_AUDIO"
  | "SET_AUDIO_VOLUME"
  | "STOP_AUDIO"
  | "assist_inbox"
  | "assist_thread"
  | "audio"
  | "channel_history"
  | "channel_msg"
  | "channel_msg_delete"
  | "channel_online"
  | "channel_pin"
  | "channel_reaction"
  | "channel_topic"
  | "channel_typing"
  | "channel_unread"
  | "channels_list"
  | "community_kudos"
  | "community_milestone"
  | "compose_preview"
  | "editor_close"
  | "editor_open"
  | "editor_status"
  | "image"
  | "logout"
  | "play_music"
  | "play_yt"
  | "player_mention"
  | "stop_music"
  | "stop_music_now"
  | "ticket_alert"
  | "ticket_inbox"
  | "ticket_msg"
  | "ticket_thread"
  | "ui_component"
  | "ui_remove"
  | "video"
  | "web_panel"
  | "youtube"
  | "yt_set_loop";

export interface OobEventMap {
  "PLAY_AUDIO": PlayAudioPayload;
  "SET_AUDIO_VOLUME": SetAudioVolumePayload;
  "STOP_AUDIO": StopAudioPayload;
  "assist_inbox": AssistInboxPayload;
  "assist_thread": AssistThreadPayload;
  "audio": AudioPayload;
  "channel_history": ChannelHistoryPayload;
  "channel_msg": ChannelMsgPayload;
  "channel_msg_delete": ChannelMsgDeletePayload;
  "channel_online": ChannelOnlinePayload;
  "channel_pin": ChannelPinPayload;
  "channel_reaction": ChannelReactionPayload;
  "channel_topic": ChannelTopicPayload;
  "channel_typing": ChannelTypingPayload;
  "channel_unread": ChannelUnreadPayload;
  "channels_list": ChannelsListPayload;
  "community_kudos": CommunityKudosPayload;
  "community_milestone": CommunityMilestonePayload;
  "compose_preview": ComposePreviewPayload;
  "editor_close": EditorClosePayload;
  "editor_open": EditorOpenPayload;
  "editor_status": EditorStatusPayload;
  "image": ImagePayload;
  "logout": LogoutPayload;
  "play_music": PlayMusicPayload;
  "play_yt": PlayYtPayload;
  "player_mention": PlayerMentionPayload;
  "stop_music": StopMusicPayload;
  "stop_music_now": StopMusicNowPayload;
  "ticket_alert": TicketAlertPayload;
  "ticket_inbox": TicketInboxPayload;
  "ticket_msg": TicketMsgPayload;
  "ticket_thread": TicketThreadPayload;
  "ui_component": UiComponentPayload;
  "ui_remove": UiRemovePayload;
  "video": VideoPayload;
  "web_panel": WebPanelPayload;
  "youtube": YoutubePayload;
  "yt_set_loop": YtSetLoopPayload;
}
