// AUTO-GENERATED by evennia.server.protocol.gen_ts from the OOB event registry.
// Do not edit by hand; edit the event modules and regenerate.

export interface AssistInboxPayload {
  threads: any[];
}

export interface AssistThreadPayload {
  account_id: any;
  account_key: string;
  messages: any[];
}

/** args[0] = audio URL. */
export type AudioPayload = string;

/** channel_key -> list of message rows. */
export type ChannelHistoryPayload = Record<string, Record<string, any>>;

export interface ChannelMsgPayload {
  channel: string;
  text: string;
  html?: string;
  sender: string;
  platform?: string;
  ts: number;
  msg_id: string;
}

export interface ChannelMsgDeletePayload {
  channel: string;
  msg_id: string;
}

/** channel_key -> count. */
export type ChannelOnlinePayload = Record<string, Record<string, any>>;

export interface ChannelPinPayload {
  channel_key: string;
  action?: string;
  msg_id?: string;
  text?: string;
  pinned_by?: string;
}

export interface ChannelReactionPayload {
  channel_key: string;
  msg_id: string;
  emoji: string;
  count?: number;
  delta?: number;
  sender_name?: string;
}

export interface ChannelTopicPayload {
  channel_key: string;
  topic: string;
}

export interface ChannelTypingPayload {
  channel_key: string;
  sender_name: string;
  platform?: string;
}

/** channel_key -> count. */
export type ChannelUnreadPayload = Record<string, Record<string, any>>;

/** Full channel registry; args[0] is a list of channel dicts. */
export type ChannelsListPayload = any[];

/** args[0] = image URL. */
export type ImagePayload = string;

/** args[0] = reason (e.g. 'quit'). */
export type LogoutPayload = string;

export interface PlayerMentionPayload {
  channel: string;
  msg_id: string;
  sender: string;
  text: string;
}

export interface TicketAlertPayload {
  id: string;
  label: string;
  who: string;
  age_mins: number;
}

export interface TicketInboxPayload {
  tickets: any[];
}

export interface TicketMsgPayload {
  id: string;
  kind: string;
  text: string;
  html?: string;
  sender: string;
  platform?: string;
  visibility?: string;
  ts: number;
  status?: string;
}

/** A full ticket dict (see tickets.core.to_dict). */
export type TicketThreadPayload = Record<string, any>;

/** A UI component spec (see evennia.server.ui). */
export type UiComponentPayload = Record<string, any>;

export interface UiRemovePayload {
  id: string;
}

/** args[0] = video URL. */
export type VideoPayload = string;

/** args[0] = YouTube URL. */
export type YoutubePayload = string;

export type OobEvent =
  | "assist_inbox"
  | "assist_thread"
  | "audio"
  | "channel_history"
  | "channel_msg"
  | "channel_msg_delete"
  | "channel_online"
  | "channel_pin"
  | "channel_reaction"
  | "channel_topic"
  | "channel_typing"
  | "channel_unread"
  | "channels_list"
  | "image"
  | "logout"
  | "player_mention"
  | "ticket_alert"
  | "ticket_inbox"
  | "ticket_msg"
  | "ticket_thread"
  | "ui_component"
  | "ui_remove"
  | "video"
  | "youtube";

export interface OobEventMap {
  "assist_inbox": AssistInboxPayload;
  "assist_thread": AssistThreadPayload;
  "audio": AudioPayload;
  "channel_history": ChannelHistoryPayload;
  "channel_msg": ChannelMsgPayload;
  "channel_msg_delete": ChannelMsgDeletePayload;
  "channel_online": ChannelOnlinePayload;
  "channel_pin": ChannelPinPayload;
  "channel_reaction": ChannelReactionPayload;
  "channel_topic": ChannelTopicPayload;
  "channel_typing": ChannelTypingPayload;
  "channel_unread": ChannelUnreadPayload;
  "channels_list": ChannelsListPayload;
  "image": ImagePayload;
  "logout": LogoutPayload;
  "player_mention": PlayerMentionPayload;
  "ticket_alert": TicketAlertPayload;
  "ticket_inbox": TicketInboxPayload;
  "ticket_msg": TicketMsgPayload;
  "ticket_thread": TicketThreadPayload;
  "ui_component": UiComponentPayload;
  "ui_remove": UiRemovePayload;
  "video": VideoPayload;
  "youtube": YoutubePayload;
}
