// AUTO-GENERATED by evennia.server.protocol.gen_ts from the OOB event registry.
// Do not edit by hand; edit the event modules and regenerate.

export interface PlayAudioPayload {
  url: string;
  loop?: boolean;
  volume?: number;
  fade_in?: number;
}

export interface SetAudioVolumePayload {
  volume: number;
  fade?: number;
}

export interface StopAudioPayload {
  fade_out?: number;
}

export interface ActivityBatchPayload {
  stream_id: string;
  first_seq: number;
  last_seq: number;
  events: any[];
}

export interface ActivityRolePayload {
  allowed: boolean;
  can_puppet: boolean;
}

export interface AssistInboxPayload {
  threads: any[];
}

export interface AssistThreadPayload {
  account_id: any;
  account_key: string;
  messages: any[];
}

/** args[0] = audio URL. */
export type AudioPayload = string;

/** channel_key -> list of message rows. */
export type ChannelHistoryPayload = Record<string, Record<string, any>>;

export interface ChannelMsgPayload {
  channel: string;
  text: string;
  html?: string;
  sender: string;
  sender_html?: string;
  platform?: string;
  ts: number;
  msg_id: string;
}

export interface ChannelMsgDeletePayload {
  channel: string;
  msg_id: string;
}

/** channel_key -> count. */
export type ChannelOnlinePayload = Record<string, Record<string, any>>;

export interface ChannelPinPayload {
  channel_key: string;
  action?: string;
  msg_id?: string;
  text?: string;
  pinned_by?: string;
}

export interface ChannelReactionPayload {
  channel_key: string;
  msg_id: string;
  emoji: string;
  count?: number;
  delta?: number;
  sender_name?: string;
}

export interface ChannelTopicPayload {
  channel_key: string;
  topic: string;
}

export interface ChannelTypingPayload {
  channel_key: string;
  sender_name: string;
  platform?: string;
}

/** channel_key -> count. */
export type ChannelUnreadPayload = Record<string, Record<string, any>>;

/** Full channel registry; args[0] is a list of channel dicts. */
export type ChannelsListPayload = any[];

export interface CommunityKudosPayload {
  receiver: string;
  message: string;
  anonymous: boolean;
  giver?: string;
}

export interface CommunityMilestonePayload {
  label: string;
}

/** Reachable verbs and !social tokens for Tab completion. */
export interface CompletionLexiconPayload {
  verbs: any[];
}

/** Live preview of a pose/emote/say before it is sent. */
export interface ComposePreviewPayload {
  you: string;
  room: string;
  error?: string;
}

/** args[0] = session_id; the server closed the editor. */
export type EditorClosePayload = string;

/** args = [session_id, buffer, meta]; open the editor overlay. */
export type EditorOpenPayload = any[];

/** args[0] = 'saved' | 'unsaved'. */
export type EditorStatusPayload = string;

/** A help page: index, category, topic, section, search, or not_found. */
export interface HelpViewPayload {
  kind: string;
  query: string;
  categories?: any[];
  category?: string;
  topics?: any[];
  topic?: Record<string, any>;
  section?: string;
  hits?: any[];
  suggestions?: any[];
}

/** args[0] = image URL. */
export type ImagePayload = string;

/** The authenticated session state was refreshed. */
export type LoggedInPayload = Record<string, any>;

/** args[0] = reason (e.g. 'quit'). */
export type LogoutPayload = string;

/** args[0] = audio URL. */
export type PlayMusicPayload = string;

/** args = [yt_id, offset_seconds, loop(0|1)]; start room/DJ music. */
export type PlayYtPayload = any[];

export interface PlayerMentionPayload {
  channel: string;
  msg_id: string;
  sender: string;
  text: string;
}

/** The session's SCREENREADER flag, sent whenever it is set (login restore, @option). */
export interface ScreenreaderModePayload {
  on: boolean;
}

/** Fade the current track out. */
export interface StopMusicPayload {
  fade_out?: number;
}

/** Cut playback immediately. */
export type StopMusicNowPayload = any;

/** args[0] = the token of a `text_done` input whose command has finished. */
export type TextDonePayload = string;

export interface TicketAlertPayload {
  id: string;
  label: string;
  who: string;
  age_mins: number;
  ref?: string;
  title?: string;
  level?: string;
  held?: boolean;
}

export interface TicketInboxPayload {
  tickets: any[];
}

/** One message on a ticket, pushed live. origin is staff, player or system; audience is owner, assignee or staff (who this copy is for); news is false for a claim or an assignment, which a player is not told is unread. */
export interface TicketMsgPayload {
  id: string;
  kind: string;
  text: string;
  html?: string;
  sender: string;
  sender_html?: string;
  platform?: string;
  visibility?: string;
  ts: number;
  status?: string;
  short_id?: string;
  number?: number;
  ref?: string;
  label?: string;
  title?: string;
  subject?: string;
  origin?: string;
  audience?: string;
  news?: boolean;
}

/** Lean ticket protocol: a puppet requester came, went or moved. sort is the row's new order key. */
export interface TicketPresencePayload {
  id: string;
  presence: string;
  seen: number;
  sort: any[];
  account_online?: boolean;
}

/** Lean ticket protocol: the ticket left the open queue (closed, withdrawn, decided). */
export interface TicketRemovePayload {
  id: string;
}

/** Whether this session works the staff ticket queue, who it is, and whether it is on duty. Sent at login and on @sync_channels. */
export interface TicketRolePayload {
  staff: boolean;
  account?: number;
  duty?: boolean;
}

/** A full ticket dict (see tickets.core.to_dict). */
export type TicketThreadPayload = Record<string, any>;

/** Sent at login to a web session: requests with a reply the player has not read, and for staff how many tickets are unanswered and how many of those nobody holds. */
export interface TicketUnreadPayload {
  mine?: number;
  unanswered?: number;
  unclaimed?: number;
}

/** Lean ticket protocol (after the ticket_hello request): one open-queue row to add or replace. why is new, reopened or changed; notify is true when this staff member should be told. */
export interface TicketUpsertPayload {
  ticket: Record<string, any>;
  why?: string;
  notify?: boolean;
}

/** A UI component spec (see evennia.server.ui). */
export type UiComponentPayload = Record<string, any>;

export interface UiRemovePayload {
  id: string;
}

/** args[0] = video URL. */
export type VideoPayload = string;

/** Open an embedded web page in the shell: args[0] = {url, title?, id?, size?}; size is wide (default) or side. */
export type WebPanelPayload = Record<string, any>;

/** args[0] = YouTube URL. */
export type YoutubePayload = string;

/** args[0] = 1|0. */
export type YtSetLoopPayload = number;

export type OobEvent =
  | "PLAY_AUDIO"
  | "SET_AUDIO_VOLUME"
  | "STOP_AUDIO"
  | "activity_batch"
  | "activity_role"
  | "assist_inbox"
  | "assist_thread"
  | "audio"
  | "channel_history"
  | "channel_msg"
  | "channel_msg_delete"
  | "channel_online"
  | "channel_pin"
  | "channel_reaction"
  | "channel_topic"
  | "channel_typing"
  | "channel_unread"
  | "channels_list"
  | "community_kudos"
  | "community_milestone"
  | "completion_lexicon"
  | "compose_preview"
  | "editor_close"
  | "editor_open"
  | "editor_status"
  | "help_view"
  | "image"
  | "logged_in"
  | "logout"
  | "play_music"
  | "play_yt"
  | "player_mention"
  | "screenreader_mode"
  | "stop_music"
  | "stop_music_now"
  | "text_done"
  | "ticket_alert"
  | "ticket_inbox"
  | "ticket_msg"
  | "ticket_presence"
  | "ticket_remove"
  | "ticket_role"
  | "ticket_thread"
  | "ticket_unread"
  | "ticket_upsert"
  | "ui_component"
  | "ui_remove"
  | "video"
  | "web_panel"
  | "youtube"
  | "yt_set_loop";

export interface OobEventMap {
  "PLAY_AUDIO": PlayAudioPayload;
  "SET_AUDIO_VOLUME": SetAudioVolumePayload;
  "STOP_AUDIO": StopAudioPayload;
  "activity_batch": ActivityBatchPayload;
  "activity_role": ActivityRolePayload;
  "assist_inbox": AssistInboxPayload;
  "assist_thread": AssistThreadPayload;
  "audio": AudioPayload;
  "channel_history": ChannelHistoryPayload;
  "channel_msg": ChannelMsgPayload;
  "channel_msg_delete": ChannelMsgDeletePayload;
  "channel_online": ChannelOnlinePayload;
  "channel_pin": ChannelPinPayload;
  "channel_reaction": ChannelReactionPayload;
  "channel_topic": ChannelTopicPayload;
  "channel_typing": ChannelTypingPayload;
  "channel_unread": ChannelUnreadPayload;
  "channels_list": ChannelsListPayload;
  "community_kudos": CommunityKudosPayload;
  "community_milestone": CommunityMilestonePayload;
  "completion_lexicon": CompletionLexiconPayload;
  "compose_preview": ComposePreviewPayload;
  "editor_close": EditorClosePayload;
  "editor_open": EditorOpenPayload;
  "editor_status": EditorStatusPayload;
  "help_view": HelpViewPayload;
  "image": ImagePayload;
  "logged_in": LoggedInPayload;
  "logout": LogoutPayload;
  "play_music": PlayMusicPayload;
  "play_yt": PlayYtPayload;
  "player_mention": PlayerMentionPayload;
  "screenreader_mode": ScreenreaderModePayload;
  "stop_music": StopMusicPayload;
  "stop_music_now": StopMusicNowPayload;
  "text_done": TextDonePayload;
  "ticket_alert": TicketAlertPayload;
  "ticket_inbox": TicketInboxPayload;
  "ticket_msg": TicketMsgPayload;
  "ticket_presence": TicketPresencePayload;
  "ticket_remove": TicketRemovePayload;
  "ticket_role": TicketRolePayload;
  "ticket_thread": TicketThreadPayload;
  "ticket_unread": TicketUnreadPayload;
  "ticket_upsert": TicketUpsertPayload;
  "ui_component": UiComponentPayload;
  "ui_remove": UiRemovePayload;
  "video": VideoPayload;
  "web_panel": WebPanelPayload;
  "youtube": YoutubePayload;
  "yt_set_loop": YtSetLoopPayload;
}
