// Generate the xterm-256 colour palette CSS that matches evennia.utils.text2html
// parse_html output: `.color-NNN` (foreground) and `.bgcolor-NNN` (background),
// NNN zero-padded 000..255. Run: `node scripts/gen-palette.mjs`.
//
// The palette is standard xterm-256:
//   0-15    base 16 ANSI colours
//   16-231  6x6x6 colour cube
//   232-255 grayscale ramp
// Games may override any `.color-NNN` in their theme; this is the neutral base.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const base16 = [
  "000000", "800000", "008000", "808000", "000080", "800080", "008080", "c0c0c0",
  "808080", "ff0000", "00ff00", "ffff00", "0000ff", "ff00ff", "00ffff", "ffffff",
];
const cube = [0, 95, 135, 175, 215, 255];
const hex = (n) => n.toString(16).padStart(2, "0");

function colorFor(i) {
  if (i < 16) return base16[i];
  if (i < 232) {
    const n = i - 16;
    const r = cube[Math.floor(n / 36) % 6];
    const g = cube[Math.floor(n / 6) % 6];
    const b = cube[n % 6];
    return `${hex(r)}${hex(g)}${hex(b)}`;
  }
  const v = 8 + (i - 232) * 10;
  return `${hex(v)}${hex(v)}${hex(v)}`;
}

const lines = [
  "/* GENERATED by scripts/gen-palette.mjs. Do not edit by hand.",
  "   xterm-256 palette matching evennia parse_html color-NNN / bgcolor-NNN. */",
  "",
];
for (let i = 0; i < 256; i++) {
  const pad = String(i).padStart(3, "0");
  lines.push(`.color-${pad}{color:#${colorFor(i)}}`);
}
for (let i = 0; i < 256; i++) {
  const pad = String(i).padStart(3, "0");
  lines.push(`.bgcolor-${pad}{background-color:#${colorFor(i)}}`);
}
// text2html extras that parse_html can emit as classes.
lines.push(".blink{animation:ev-blink 1s step-end infinite}");
lines.push(":root[data-calm] .blink{animation:none}");
lines.push(".underline{text-decoration:underline}");
lines.push("@keyframes ev-blink{50%{opacity:0}}");
lines.push("");

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../src/styles/ansi-palette.css");
writeFileSync(out, lines.join("\n"));
console.log(`wrote ${out} (256 fg + 256 bg + extras)`);
