# Generated by Django 2.2.16 on 2021-05-14 20:32

from django.db import migrations


def migrate_channel_aliases(apps, schema_editor):
    """
    One-time data migration creating per-subscriber channel aliases for
    channels that predate that feature.

    Whether there is anything to migrate is checked via the *historical* model,
    so the query only references columns that exist at this point in migration
    history. On a fresh install the channel table is empty and this is a clean
    no-op. The actual migration needs alias/nick helpers that live on the
    current model, so it imports that; but the current model also selects
    ``db_attrs`` (a column added by a later migration), hence we only touch it
    once real channel data is known to exist, and narrowly skip if the schema
    those helpers expect has not been migrated in yet.
    """
    # Historical model: its query does not reference later-added columns.
    if not apps.get_model("comms", "ChannelDB").objects.exists():
        return

    from django.db.utils import OperationalError, ProgrammingError

    from evennia.comms.models import ChannelDB

    try:
        channels = list(ChannelDB.objects.all())
    except (OperationalError, ProgrammingError) as err:
        # The current model references schema added by later migrations that
        # have not run yet on this upgrade; nothing can be done here.
        print(
            f"channel-alias data migration 0019_auto_20210514_2032 skipped (schema not ready): {err}"
        )
        return

    for channel in channels:
        try:
            chan_key = channel.db_key.lower()
            channel_aliases = [chan_key] + [alias.lower() for alias in channel.aliases.all()]
            for subscriber in channel.subscriptions.all():
                nicktuples = subscriber.nicks.get(
                    category="channel", return_tuple=True, return_list=True
                )
                all_aliases = channel_aliases + [
                    tup[2] for tup in nicktuples if tup[3].lower() == chan_key
                ]
                for key_or_alias in all_aliases:
                    channel.add_user_channel_alias(subscriber, key_or_alias)
        except Exception as err:
            # Per-channel data issue; continue migrating the remaining channels.
            print(
                f"channel-alias data migration 0019_auto_20210514_2032 skipped for a channel: {err}"
            )


class Migration(migrations.Migration):
    # Non-atomic so the OperationalError/ProgrammingError catch above can skip
    # cleanly on an upgrade where later schema is not yet present (catching a DB
    # error inside an atomic block would leave the transaction unusable).
    atomic = False

    dependencies = [
        ("comms", "0018_auto_20191025_0831"),
    ]

    operations = [migrations.RunPython(migrate_channel_aliases, atomic=False)]
