# Generated by Django 6.0.4 on 2026-05-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0022_defaultchannel_alter_channeldb_id_alter_msg_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultChannel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comms.channeldb",),
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comms.defaultchannel",),
        ),
        migrations.CreateModel(
            name="AssistChannel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comms.channel",),
        ),
    ]
