# Generated by Django 6.0.5 on 2026-06-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0026_channeldb_db_attrs_gin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeldb',
            name='db_attributes',
        ),
    ]
