# Generated by Django 6.0.5 on 2026-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0020_scriptdb_db_attrs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptdb",
            name="db_attrs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSONB attribute document. Replaces the db_attributes M2M when the JSONB backend is active.",
                verbose_name="attrs",
            ),
        ),
    ]
