# Generated by Django 6.0.5 on 2026-06-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0023_remove_scriptdb_db_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopRegistryScript",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.defaultscript",),
        ),
    ]
