"""
Evennia action system (CM1).

A typed-action + rule-phase dispatch engine that replaces the cmdset model.
This package is built incrementally (see the CM1 roadmap). Phase 0f delivers
the permission/predicate layer that eliminates string locks; the remaining
modules (action, rule, engine, actor, ...) land in later phases.

Flat re-exports are added here as each module stabilizes. For now only the
permission lattice and predicate algebra are public.
"""

from .action import Action, GameObject, action
from .actor import Actor
from .context import ActionContext, ActionContextBuilder, build_context
from .default import (
    Access,
    Arrived,
    CharacterAdminRules,
    CharacterGeneralRules,
    CharacterMovementRules,
    CharacterObjectRules,
    CharacterSystemRules,
    Connect,
    ContainerPutRules,
    Create,
    DefaultAccountRules,
    Departed,
    Drop,
    Emit,
    Encoding,
    Enter,
    Enterable,
    EnterableObjectRules,
    ExitTraversalRules,
    Force,
    Get,
    Give,
    Help,
    Home,
    Info,
    Locomotion,
    Move,
    Moved,
    Nick,
    NickRules,
    Option,
    Password,
    Perm,
    Put,
    Py,
    PyRules,
    Screenreader,
    SessionLoginRules,
    Systems,
    Tasks,
    UserPassword,
    Wall,
    exit_resolver,
    register_exit_resolver,
)
from .dispatch import (
    DispatchMiddleware,
    ProfilingMiddleware,
    clear_middlewares,
    get_middlewares,
    register_middleware,
    try_action_dispatch,
)
from .engine import RuleEngine, engine
from .events import Event, EventRegistry, EventSpec, event_registry, subscribe
from .exceptions import ActionError, AmbiguousTarget, ParseError, RuleConflict
from .menus import (
    DisambiguationState,
    InputCaptureState,
    MenuInputAction,
    MenuPrompt,
    ask_yes_no,
    confirm,
    format_menu_prompt,
    get_input,
    paginate,
    parse_menu_choice,
)
from .muxargs import ArgAction, MuxArgs, mux_parse
from .parser import (
    ActionParser,
    DynamicVerbResolver,
    LoginStartAction,
    NoInputAction,
    NoMatchAction,
    ParseResult,
    parser,
)
from .perception import (
    filter_visible,
    get_visibility_filter,
    is_visible,
    set_visibility_filter,
)
from .permission import (
    STAFF,
    Capability,
    DefaultCapability,
    Scope,
    capability_for_name,
    get_capability_enum,
    rank_order,
    resolve_capabilities,
)
from .predicate import (
    ALWAYS,
    NEVER,
    Admin,
    And,
    Builder,
    Developer,
    Guest,
    HasAttr,
    HasCapability,
    HasTag,
    Helper,
    Holds,
    InSameRoom,
    IsAlive,
    IsObject,
    IsSelf,
    LegacyLock,
    Not,
    Or,
    Player,
    Predicate,
    coerce_predicate,
    from_lockstring,
)
from .process import (
    Activity,
    active_activity,
    cancel_activity,
    get_activities,
    is_active,
    start_activity,
)
from .registry import ActionRegistry, RuleRegistry, action_registry, rule_registry
from .result import (
    CLAIM,
    FAIL,
    PASS,
    REDIRECT,
    SILENT_FAIL,
    SKIP,
    ActionTrace,
    PhaseTrace,
    RuleResult,
)
from .rule import PHASES, RuleSpec, rule
from .state import StateProvider, enter_state, exit_state, get_states, has_state

__all__ = [
    "Capability",
    "DefaultCapability",
    "Scope",
    "STAFF",
    "get_capability_enum",
    "rank_order",
    "resolve_capabilities",
    "capability_for_name",
    "Predicate",
    "HasCapability",
    "Holds",
    "HasTag",
    "HasAttr",
    "IsSelf",
    "IsObject",
    "And",
    "Or",
    "Not",
    "Builder",
    "Admin",
    "Developer",
    "Player",
    "Helper",
    "Guest",
    "IsAlive",
    "InSameRoom",
    "ALWAYS",
    "NEVER",
    "coerce_predicate",
    "from_lockstring",
    "LegacyLock",
    # exceptions
    "ActionError",
    "RuleConflict",
    "ParseError",
    "AmbiguousTarget",
    # results + trace
    "RuleResult",
    "PASS",
    "SKIP",
    "CLAIM",
    "SILENT_FAIL",
    "FAIL",
    "REDIRECT",
    "PhaseTrace",
    "ActionTrace",
    # rules + registry
    "rule",
    "RuleSpec",
    "PHASES",
    "ActionRegistry",
    "RuleRegistry",
    "action_registry",
    "rule_registry",
    # actions
    "Action",
    "action",
    "GameObject",
    # engine + context
    "ActionContext",
    "ActionContextBuilder",
    "build_context",
    "RuleEngine",
    "engine",
    # events + activities
    "Event",
    "subscribe",
    "EventSpec",
    "EventRegistry",
    "event_registry",
    "Activity",
    "start_activity",
    "cancel_activity",
    "get_activities",
    "active_activity",
    "is_active",
    # parser + system actions
    "ParseResult",
    "ActionParser",
    "parser",
    "NoInputAction",
    "NoMatchAction",
    "LoginStartAction",
    "DynamicVerbResolver",
    # mux-style argument parsing
    "ArgAction",
    "MuxArgs",
    "mux_parse",
    # actor + state
    "Actor",
    "set_visibility_filter",
    "get_visibility_filter",
    "is_visible",
    "filter_visible",
    "StateProvider",
    "enter_state",
    "exit_state",
    "has_state",
    "get_states",
    # interaction states
    "MenuInputAction",
    "MenuPrompt",
    "InputCaptureState",
    "DisambiguationState",
    "format_menu_prompt",
    "parse_menu_choice",
    "confirm",
    "paginate",
    "get_input",
    "ask_yes_no",
    # default actions (shipped movement substrate)
    "Moved",
    "Departed",
    "Arrived",
    "Move",
    "Locomotion",
    "ExitTraversalRules",
    "CharacterMovementRules",
    "exit_resolver",
    "register_exit_resolver",
    # default actions (shipped object-manipulation substrate)
    "Enterable",
    "Get",
    "Drop",
    "Give",
    "Put",
    "Enter",
    "CharacterObjectRules",
    "ContainerPutRules",
    "EnterableObjectRules",
    # default actions (shipped admin/general/account/system/unloggedin verbs)
    "Emit",
    "Wall",
    "Force",
    "Perm",
    "Access",
    "CharacterAdminRules",
    "Nick",
    "Home",
    "Help",
    "NickRules",
    "CharacterGeneralRules",
    "Option",
    "Password",
    "UserPassword",
    "DefaultAccountRules",
    "Systems",
    "Tasks",
    "Py",
    "PyRules",
    "CharacterSystemRules",
    "Connect",
    "Create",
    "Info",
    "Encoding",
    "Screenreader",
    "SessionLoginRules",
    # cmdhandler bridge (Phase 4)
    "try_action_dispatch",
    "DispatchMiddleware",
    "ProfilingMiddleware",
    "register_middleware",
    "clear_middlewares",
    "get_middlewares",
]
