"""Movement mixin for DefaultObject."""

from django.conf import settings
from django.utils.translation import gettext as _

from evennia.hooks import hook
from evennia.objects.models import ObjectDB
from evennia.server.signals import SIGNAL_EXIT_TRAVERSED
from evennia.utils import logger
from evennia.utils.utils import is_veto, make_iter


class MoveResult:
    """
    Truthful outcome of :meth:`MovementMixin.move_to`.

    The boolean value (``bool(result)``) is the *committed* flag: whether the
    object physically changed location. This is deliberately decoupled from
    hook success. Once the location has been committed, a failure in a
    post-commit hook (``announce_move_to``, ``at_post_leave``,
    ``at_post_arrive``, ``at_post_move``) is isolated and recorded in
    :attr:`hook_errors` but does **not** make the result falsy: the move
    happened, so a caller must not treat it as a failure and retry.

    A falsy result means the move never happened (a pre-commit veto,
    exception, or a raised ``location`` assignment) and the object is exactly
    where it started.

    Attributes:
        committed (bool): Whether ``location`` was changed. Drives truthiness.
        vetoed (bool): True when a pre-move hook vetoed the move.
        failed_stage (str or None): The stage that aborted an uncommitted
            move, or the first post-commit stage that raised.
        hook_errors (list): ``(stage, exception)`` tuples from post-commit
            hooks that raised. Always empty for an uncommitted move.
    """

    __slots__ = ("committed", "vetoed", "failed_stage", "hook_errors")

    def __init__(self, committed, vetoed=False, failed_stage=None, hook_errors=None):
        self.committed = committed
        self.vetoed = vetoed
        self.failed_stage = failed_stage
        self.hook_errors = hook_errors if hook_errors is not None else []

    def __bool__(self):
        return bool(self.committed)

    def __eq__(self, other):
        # Backwards-compatible with the old ``bool`` return: ``== True`` /
        # ``== False`` keep working against the committed flag.
        if isinstance(other, bool):
            return bool(self.committed) is other
        if isinstance(other, MoveResult):
            return (
                self.committed == other.committed
                and self.vetoed == other.vetoed
                and self.failed_stage == other.failed_stage
            )
        return NotImplemented

    def __hash__(self):
        return hash(bool(self.committed))

    def __repr__(self):
        return (
            f"<MoveResult committed={self.committed} vetoed={self.vetoed} "
            f"failed_stage={self.failed_stage!r} hook_errors={len(self.hook_errors)}>"
        )


class MovementMixin:
    """Mixin providing movement-related methods for DefaultObject."""

    def move_to(
        self,
        destination,
        quiet=False,
        emit_to_obj=None,
        use_destination=True,
        to_none=False,
        move_hooks=True,
        move_type="move",
        **kwargs,
    ):
        """
        Moves this object to a new location.

        Args:
            destination (DefaultObject): Reference to the object to move to. This
                can also be an exit object, in which case the
                destination property is used as destination.
            quiet (bool): If true, turn off the calling of the emit hooks
                (announce_move_to/from etc)
            emit_to_obj (DefaultObject): object to receive error messages
            use_destination (bool): Default is for objects to use the "destination"
                 property of destinations as the target to move to. Turning off this
                 keyword allows objects to move "inside" exit objects.
            to_none (bool): Allow destination to be None. Note that no hooks are run when
                 moving to a None location. If you want to run hooks, run them manually
                 (and make sure they can manage None locations).
            move_hooks (bool): If False, turn off the calling of move-related hooks
                (at_pre/post_move etc) with quiet=True, this is as quiet a move
                as can be done.
            move_type (str): The "kind of move" being performed, such as "teleport", "traverse",
                "get", "give", or "drop". The value can be arbitrary. By default, it only affects
                the text message generated by announce_move_to and announce_move_from by defining
                their {"type": move_type} for outgoing text. This can be used for altering
                messages and/or overloaded hook behaviors.
            **kwargs: Passed on to all movement- and announcement hooks. Use in your game to let
                hooks know about any special condition of the move (such as running or sneaking).
                Exits will pass an "exit_obj" kwarg.

        Returns:
            MoveResult: A truthful, bool-compatible result. It is truthy when
            the object actually moved (``location`` committed) and falsy only
            when the move never happened (pre-commit veto or exception). A
            post-commit hook failure is recorded in ``result.hook_errors`` but
            keeps the result truthy — the move happened, so callers must not
            retry. Legacy ``if obj.move_to(...)`` / ``if not obj.move_to(...)``
            checks keep working unchanged. Error messages may still be sent to
            `emit_to_obj` for pre-commit failures.

        Notes:
            No access checks are done in this method, these should be handled before
            calling `move_to`.

        The `DefaultObject` hooks called (if `move_hooks=True`) are, in order:

        1. `self.at_pre_move(destination)` (veto rule: see `is_veto`)
        2. `source_location.at_pre_leave(self, destination)` (veto rule)
        3. `destination.at_pre_arrive(self, source_location)` (veto rule)
        4. `self.announce_move_from(destination)`
        5. (move happens here)
        6. `self.announce_move_to(source_location)`
        7. `source_location.at_post_leave(self, destination)`
        8. `destination.at_post_arrive(self, source_location)`
        9. `self.at_post_move(source_location)`

        Veto-capable pre-hooks follow the universal rule in
        `evennia.utils.utils.is_veto`: returning `False` (or any non-None
        falsy value) aborts the move; `None` is treated as "no opinion"
        and allows the move. Implicit `None` from a side-effect-only
        override does NOT veto.

        `at_post_leave` and `at_post_arrive` are unordered relative to
        each other; both fire before mover-side `at_post_move`.

        """

        def logerr(string="", err=None):
            """Simple log helper method"""
            logger.log_trace()
            self.msg("%s%s" % (string, "" if err is None else " (%s)" % err))
            return

        def logpost(stage, err):
            """Log a post-commit hook failure without telling the mover the
            move failed (it did not — the location is already committed)."""
            logger.log_trace(
                "move_to: post-commit hook %s() raised after the move committed "
                "(move stands); %s" % (stage, err)
            )

        errtxt = _("Couldn't perform move ({err}). Contact an admin.")
        if not emit_to_obj:
            emit_to_obj = self

        if not destination:
            if to_none:
                # immediately move to None. There can be no hooks called since
                # there is no destination to call them with.
                self.location = None
                return MoveResult(committed=True)
            emit_to_obj.msg(_("The destination doesn't exist."))
            return MoveResult(committed=False, failed_stage="no_destination")
        if destination.destination and use_destination:
            # traverse exits
            destination = destination.destination

        # Save the old location
        source_location = self.location

        # Before the move, call pre-hooks. Veto semantics use is_veto():
        # only an explicit non-None falsy return aborts the move. None
        # (the implicit return of an override that forgot the explicit
        # `return True`) is treated as "no opinion / allow".
        if move_hooks:
            # check if we are okay to move
            try:
                if is_veto(self.at_pre_move(destination, move_type=move_type, **kwargs)):
                    return MoveResult(committed=False, vetoed=True, failed_stage="at_pre_move")
            except Exception as err:
                logerr(errtxt.format(err="at_pre_move()"), err)
                return MoveResult(committed=False, failed_stage="at_pre_move")
            # check if source location lets us go
            try:
                if source_location and is_veto(
                    source_location.at_pre_leave(self, destination, move_type=move_type, **kwargs)
                ):
                    return MoveResult(committed=False, vetoed=True, failed_stage="at_pre_leave")
            except Exception as err:
                logerr(errtxt.format(err="at_pre_leave()"), err)
                return MoveResult(committed=False, failed_stage="at_pre_leave")
            # check if destination accepts us
            try:
                if destination and is_veto(
                    destination.at_pre_arrive(self, source_location, move_type=move_type, **kwargs)
                ):
                    return MoveResult(committed=False, vetoed=True, failed_stage="at_pre_arrive")
            except Exception as err:
                logerr(errtxt.format(err="at_pre_arrive()"), err)
                return MoveResult(committed=False, failed_stage="at_pre_arrive")

        if not quiet:
            # tell the old room we are leaving (still pre-commit: a failure
            # here aborts before location changes)
            try:
                self.announce_move_from(destination, move_type=move_type, **kwargs)
            except Exception as err:
                logerr(errtxt.format(err="announce_move_from()"), err)
                return MoveResult(committed=False, failed_stage="announce_move_from")

        # Perform move. This is the commit point: everything after it must not
        # report an uncommitted failure, because the object HAS moved.
        try:
            self.location = destination
        except Exception as err:
            logerr(errtxt.format(err="location change"), err)
            return MoveResult(committed=False, failed_stage="location")

        # --- committed past this line; post-commit hooks are isolated ---
        hook_errors = []

        # Invalidate the location-cmdset cache for both sides: the set of
        # commands available in each room depends on what objects are
        # present, and the cache key is keyed by location generation.
        try:
            from evennia.commands.location_cmdset_cache import bump_cmdset_generation

            if source_location is not None:
                bump_cmdset_generation(source_location)
            if destination is not None and destination is not source_location:
                bump_cmdset_generation(destination)
        except Exception:
            logger.log_trace("move_to: cmdset-cache invalidation failed")

        # Scope state is cached independently from principal grants. A move can
        # change derived location/provider labels, so invalidate only the moved
        # resource side and leave slow-changing grant caches warm.
        try:
            from evennia.authorization.storage import bump_resource_generation

            bump_resource_generation(self)
        except Exception:
            logger.log_trace("move_to: authorization-scope invalidation failed")

        if not quiet:
            # Tell the new room we are there.
            try:
                self.announce_move_to(source_location, move_type=move_type, **kwargs)
            except Exception as err:
                logpost("announce_move_to", err)
                hook_errors.append(("announce_move_to", err))

        if move_hooks:
            # Post-leave on the source room; object is no longer here.
            if source_location:
                try:
                    source_location.at_post_leave(self, destination, move_type=move_type, **kwargs)
                except Exception as err:
                    logpost("at_post_leave", err)
                    hook_errors.append(("at_post_leave", err))
            # Post-arrive on the destination; object is now here.
            try:
                destination.at_post_arrive(self, source_location, move_type=move_type, **kwargs)
            except Exception as err:
                logpost("at_post_arrive", err)
                hook_errors.append(("at_post_arrive", err))

        # Execute eventual extra commands on this object after moving it
        # (usually calling 'look')
        if move_hooks:
            try:
                self.at_post_move(source_location, move_type=move_type, **kwargs)
            except Exception as err:
                logpost("at_post_move", err)
                hook_errors.append(("at_post_move", err))
        return MoveResult(
            committed=True,
            failed_stage=hook_errors[0][0] if hook_errors else None,
            hook_errors=hook_errors,
        )

    def clear_exits(self):
        """
        Destroys all of the exits and any exits pointing to this
        object as a destination.

        """
        for out_exit in [exi for exi in ObjectDB.objects.get_contents(self) if exi.db_destination]:
            out_exit.delete()
        for in_exit in ObjectDB.objects.filter(db_destination=self):
            in_exit.delete()

    def clear_contents(self):
        """
        Moves all objects (accounts/things) to their home location or
        to default home.

        """
        # Gather up everything that thinks this is its location.
        default_home_id = int(settings.DEFAULT_HOME.lstrip("#"))
        try:
            default_home = ObjectDB.objects.get(id=default_home_id)
            if default_home.dbid == self.dbid:
                # we are deleting default home!
                default_home = None
        except Exception:
            string = _("Could not find default home '(#{dbid})'.")
            logger.log_err(string.format(dbid=default_home_id))
            default_home = None

        for obj in self.contents:
            home = obj.home
            # Obviously, we can't send it back to here.
            if not home or (home and home.dbid == self.dbid):
                obj.home = default_home
                home = default_home

            # If for some reason it's still None...
            if not home:
                obj.location = None
                obj.msg(_("Something went wrong! You are dumped into nowhere. Contact an admin."))
                logger.log_err(
                    "Missing default home - '{name}(#{dbid})' now has a null location.".format(
                        name=obj.name, dbid=obj.dbid
                    )
                )
                return

            if obj.is_puppeted:
                if home:
                    string = _(
                        "Your current location has ceased to exist, moving you to (#{dbid})."
                    )
                    obj.msg(string.format(dbid=home.dbid))
                else:
                    # Famous last words: The account should never see this.
                    obj.msg(_("This place should not exist ... contact an admin."))
            obj.move_to(home, move_type="teleport")

    @hook(
        event="move",
        phase="pre",
        actor="mover",
        returns="veto",
        discipline="public",
        fires_from=("MovementMixin.move_to",),
        notes="Fires on the mover. Veto aborts: no mover-side or location-side post-hooks fire.",
    )
    def at_pre_move(self, destination, move_type="move", **kwargs):
        """
        Called just before starting to move this object to destination.

        Veto rule: return `False` (or any non-None falsy value) to abort.
        Return `True`, `None`, or any other truthy value to allow the move.
        See `evennia.utils.utils.is_veto` for the canonical rule.

        Args:
            destination (DefaultObject): The object we are moving to.
            move_type (str): The type of move. "give", "traverse", etc.
                Arbitrary string provided to `obj.move_to()`. Useful for
                altering messages or logic depending on the kind of move.
            **kwargs: Arbitrary, optional arguments for users overriding
                the call (unused by default).

        Fixture and anchored placement permit only explicit teleportation. This
        makes fixed placement a containment invariant rather than a
        command-specific pickup check; ordinary get, give, put, and scripted
        moves all veto.

        Returns:
            bool or None: `False` (or non-None falsy) to abort the move,
            otherwise allow it.

        """
        if getattr(self, "is_fixed", False) and move_type != "teleport":
            mover = kwargs.get("mover") or kwargs.get("move_initiator")
            recipient = mover or (destination if hasattr(destination, "msg") else None)
            if recipient is not None:
                if getattr(self, "is_fixture", False):
                    recipient.msg("You can't move that normally—it is installed as a fixture.")
                else:
                    recipient.msg("You can't move that normally—it is fixed in place.")
            return False
        return True

    @hook(
        event="move",
        phase="pre",
        actor="source",
        returns="veto",
        discipline="public",
        fires_from=("MovementMixin.move_to",),
        notes="Fires on the source location. Veto aborts after at_pre_move passes.",
    )
    def at_pre_leave(self, leaving_object, destination, **kwargs):
        """
        Called on this object just before another object that is currently
        'inside' it leaves. Also the place for side effects that need to run
        while `leaving_object` is still considered present here.

        Veto rule: return `False` (or any non-None falsy value) to abort.
        Return `True`, `None`, or any other truthy value to allow the move.
        Implicit `None` from a side-effect-only override does NOT veto;
        the move proceeds. See `evennia.utils.utils.is_veto` for the rule.

        Args:
            leaving_object (DefaultObject): The object that is about to leave.
            destination (DefaultObject): Where the object is going to.
            **kwargs: Arbitrary, optional arguments for users overriding
                the call (unused by default).

        Returns:
            bool or None: `False` (or non-None falsy) to abort, otherwise
            allow the move.

        """
        return True

    @hook(
        event="move",
        phase="pre",
        actor="destination",
        returns="veto",
        discipline="public",
        fires_from=("MovementMixin.move_to",),
        notes="Fires on the destination. Veto aborts after at_pre_move and at_pre_leave pass.",
    )
    def at_pre_arrive(self, arriving_object, source_location, **kwargs):
        """
        Called on this object just before it receives another object. Also
        the place for side effects that need to run before `arriving_object`
        is placed here.

        Veto rule: return `False` (or any non-None falsy value) to abort.
        Return `True`, `None`, or any other truthy value to allow the move.
        Implicit `None` from a side-effect-only override does NOT veto.
        See `evennia.utils.utils.is_veto` for the canonical rule.

        Args:
            arriving_object (DefaultObject): The object moving into this one.
            source_location (DefaultObject): Where `arriving_object` came
                from. May be `None`.
            **kwargs: Arbitrary, optional arguments for users overriding
                the call (unused by default).

        Returns:
            bool or None: `False` (or non-None falsy) to abort, otherwise
            allow the move.

        """
        return True

    # deprecated alias
    at_before_move = at_pre_move

    def announce_move_from(self, destination, msg=None, mapping=None, move_type="move", **kwargs):
        """
        Called if the move is to be announced. This is
        called while we are still standing in the old
        location.

        Args:
            destination (DefaultObject): The place we are going to.
            msg (str, optional): a replacement message.
            mapping (dict, optional): additional mapping objects.
            move_type (str): The type of move. "give", "traverse", etc.
                This is an arbitrary string provided to obj.move_to().
                Useful for altering messages or altering logic depending
                on the kind of movement.
            **kwargs: Arbitrary, optional arguments for users
                overriding the call (unused by default).

        Notes:

            You can override this method and call its parent with a
            message to simply change the default message.  In the string,
            you can use the following as mappings:

            - `{object}`: the object which is moving.
            - `{exit}`: the exit from which the object is moving (if found).
            - `{origin}`: the location of the object before the move.
            - `{destination}`: the location of the object after moving.

        """
        if not self.location:
            return
        if msg:
            string = msg
        else:
            string = _("{object} is leaving {origin}, heading for {destination}.")

        location = self.location
        exits = [
            o for o in location.contents if o.location is location and o.destination is destination
        ]
        if not mapping:
            mapping = {}

        mapping.update(
            {
                "object": self,
                "exit": exits[0] if exits else _("somewhere"),
                "origin": location or _("nowhere"),
                "destination": destination or _("nowhere"),
            }
        )

        location.msg_contents(
            (string, {"type": move_type}), exclude=(self,), from_obj=self, mapping=mapping
        )

    def announce_move_to(self, source_location, msg=None, mapping=None, move_type="move", **kwargs):
        """
        Called after the move if the move was not quiet. At this point
        we are standing in the new location.

        Args:
            source_location (DefaultObject): The place we came from
            msg (str, optional): the replacement message if location.
            mapping (dict, optional): additional mapping objects.
            move_type (str): The type of move. "give", "traverse", etc.
                This is an arbitrary string provided to obj.move_to().
                Useful for altering messages or altering logic depending
                on the kind of movement.
            **kwargs: Arbitrary, optional arguments for users
                overriding the call (unused by default).

        Notes:

            You can override this method and call its parent with a
            message to simply change the default message.  In the string,
            you can use the following as mappings (between braces):


            - `{object}`: the object which is moving.
            - `{exit}`: the exit from which the object is moving (if found).
            - `{origin}`: the location of the object before the move.
            - `{destination}`: the location of the object after moving.

        """

        if not source_location and self.location.is_puppeted:
            # This was created from nowhere and added to an account's
            # inventory; it's probably the result of a create command.
            string = _("You now have {name} in your possession.").format(
                name=self.get_display_name(self.location)
            )
            self.location.msg(string)
            return

        if source_location:
            if msg:
                string = msg
            else:
                string = _("{object} arrives to {destination} from {origin}.")
        else:
            string = _("{object} arrives to {destination}.")

        origin = source_location
        destination = self.location
        exits = []
        if origin:
            exits = [
                o
                for o in destination.contents
                if o.location is destination and o.destination is origin
            ]

        if not mapping:
            mapping = {}

        mapping.update(
            {
                "object": self,
                "exit": exits[0] if exits else _("somewhere"),
                "origin": origin or _("nowhere"),
                "destination": destination or _("nowhere"),
            }
        )

        destination.msg_contents(
            (string, {"type": move_type}), exclude=(self,), from_obj=self, mapping=mapping
        )

    @hook(
        event="move",
        phase="post",
        actor="mover",
        returns="ignored",
        discipline="public",
        fires_from=("MovementMixin.move_to",),
        notes="Fires on the mover after location-side post-hooks.",
    )
    def at_post_move(self, source_location, move_type="move", **kwargs):
        """
        Called after move has completed, regardless of quiet mode or
        not.  Allows changes to the object due to the location it is
        now in.

        Args:
            source_location (DefaultObject): Where we came from. This may be `None`.
            move_type (str): The type of move. "give", "traverse", etc.
                This is an arbitrary string provided to obj.move_to().
                Useful for altering messages or altering logic depending
                on the kind of movement.
            **kwargs: Arbitrary, optional arguments for users
                overriding the call (unused by default).

        """
        pass

    # deprecated
    at_after_move = at_post_move

    @hook(
        event="move",
        phase="post",
        actor="source",
        returns="ignored",
        discipline="public",
        fires_from=("MovementMixin.move_to",),
        notes="Fires on the source location after the move commits.",
    )
    def at_post_leave(self, moved_obj, target_location, move_type="move", **kwargs):
        """
        Called after an object has left from inside this object. At this
        point `moved_obj` is no longer in `self.contents`.

        Args:
            moved_obj (DefaultObject): The object that has left.
            target_location (DefaultObject): Where `moved_obj` went.
            move_type (str): The type of move. "give", "traverse", etc.
                This is an arbitrary string provided to obj.move_to().
                Useful for altering messages or altering logic depending
                on the kind of movement.
            **kwargs: Arbitrary, optional arguments for users
                overriding the call (unused by default).

        Notes:
            Fires unordered relative to `target_location.at_post_arrive`,
            and both fire before the mover's `at_post_move`.

        """
        pass

    @hook(
        event="move",
        phase="post",
        actor="destination",
        returns="ignored",
        discipline="public",
        fires_from=("MovementMixin.move_to",),
        notes="Fires on the destination after the move commits.",
    )
    def at_post_arrive(self, moved_obj, source_location, move_type="move", **kwargs):
        """
        Called after an object has been moved into this object. At this
        point `moved_obj` is in `self.contents`.

        Args:
            moved_obj (DefaultObject): The object moved into this one.
            source_location (DefaultObject): Where `moved_obj` came from.
                Note that this could be `None`.
            move_type (str): The type of move. "give", "traverse", etc.
                This is an arbitrary string provided to obj.move_to().
                Useful for altering messages or altering logic depending
                on the kind of movement.
            **kwargs: Arbitrary, optional arguments for users
                overriding the call (unused by default).

        Notes:
            Fires unordered relative to `source_location.at_post_leave`,
            and both fire before the mover's `at_post_move`.

        """
        pass

    def do_traverse(self, traversing_object, target_location, **kwargs):
        """
        Implementation method that performs the actual traversal, normally
        by calling `traversing_object.move_to(target_location)`. Only Exit
        objects implement this by default. Override to change *how* the
        traverse happens; for side-effect hooks prefer `at_pre_traverse`,
        `at_post_traverse`, or `at_failed_traverse`.

        Args:
            traversing_object (DefaultObject): Object traversing us.
            target_location (DefaultObject): Where target is going.
            **kwargs: Arbitrary, optional arguments for users
                overriding the call (unused by default).

        """
        pass

    @hook(
        event="traverse",
        phase="pre",
        actor="self",
        returns="veto",
        discipline="public",
        fires_from=("DefaultExit.do_traverse",),
        notes="Fires on the exit. Veto fires at_failed_traverse; move chain does NOT fire.",
    )
    def at_pre_traverse(self, traversing_object, target_location, **kwargs):
        """
        Called by `do_traverse` before the move is attempted.

        Veto rule: return `False` (or any non-None falsy value) to abort
        the traverse; `at_failed_traverse` then fires instead. Return
        `True`, `None`, or any other truthy value to allow the move.
        See `evennia.utils.utils.is_veto` for the canonical rule.

        Args:
            traversing_object (DefaultObject): Object attempting to traverse.
            target_location (DefaultObject): Where the object would go.
            **kwargs: Arbitrary, optional arguments for users overriding
                the call (unused by default).

        Returns:
            bool or None: `False` (or non-None falsy) to abort, otherwise
            allow the traverse.

        """
        return True

    @hook(
        event="traverse",
        phase="post",
        actor="self",
        returns="ignored",
        discipline="public",
        fires_from=("DefaultExit.do_traverse",),
        notes="Fires on the exit after the move chain has completed.",
    )
    def at_post_traverse(self, traversing_object, source_location, **kwargs):
        """
        Called just after an object successfully used this object to
        traverse to another object (i.e. this object is a type of
        Exit)

        Args:
            traversing_object (DefaultObject): The object traversing us.
            source_location (DefaultObject): Where `traversing_object` came from.
            **kwargs (dict): Arbitrary, optional arguments for users
                overriding the call (unused by default).

        Notes:
            The target location should normally be available as `self.destination`.
        """
        pass

    # deprecated
    at_after_traverse = at_post_traverse

    @hook(
        event="traverse",
        phase="failed",
        actor="self",
        returns="ignored",
        discipline="public",
        fires_from=("DefaultExit.do_traverse",),
        notes="Fires on the exit when at_pre_traverse vetoes.",
    )
    def at_failed_traverse(self, traversing_object, **kwargs):
        """
        This is called if an object fails to traverse this object for
        some reason.

        Args:
            traversing_object (DefaultObject): The object that failed traversing us.
            **kwargs: Arbitrary, optional arguments for users
                overriding the call (unused by default).

        Notes:
            Using the default exits, this hook will not be called if an
            Attribute `err_traverse` is defined - this will in that case be
            read for an error string instead.

        """
        pass
